version: 2
jobs:
  build:
    docker:
      - image: docker
    working_directory: /expenses
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            echo "{\"version\": \"${CIRCLE_SHA1:0:8}\"}" > frontend/src/assets/config.json
            docker build -t expenses .
      - deploy:
          name: Push Docker image
          command: |
            TAG=${CIRCLE_SHA1:0:8}
            DOCKER_HUB_IMAGE=oxisto/expenses
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag expenses $DOCKER_HUB_IMAGE
            docker tag expenses $DOCKER_HUB_IMAGE:$TAG
            docker push $DOCKER_HUB_IMAGE:$TAG
            docker push $DOCKER_HUB_IMAGE
  deploy_kubernetes:
    docker:
      - image: circleci/python
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Download kubectl
          command: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl
      - run:
          name: Retrieve kubeconfig from ENV
          command: mkdir -p ~/.kube && echo $KUBECONFIG_BASE64 | base64 -d > ~/.kube/config
      - run:
          name: Install expenses
          command: ./kubectl apply -f kubernetes/expenses.yaml
      - run:
          name: Set image to current build
          command: |
            TAG=${CIRCLE_SHA1:0:8}
            ./kubectl set image deployment expenses expenses=oxisto/expenses:$TAG
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          context: org-global
      - deploy_kubernetes:
          context: org-global
          requires:
            - build
