version: 2
jobs:
  build_server:
    docker:
      - image: docker
    working_directory: /track-expenses
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t track-expenses-server server
      - deploy:
          name: Push Docker image
          command: |
            TAG=${CIRCLE_SHA1:0:8}
            DOCKER_HUB_IMAGE=oxisto/track-expenses-server
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag track-expenses-server $DOCKER_HUB_IMAGE
            docker tag track-expenses-server $DOCKER_HUB_IMAGE:$TAG
            docker push $DOCKER_HUB_IMAGE:$TAG
            docker push $DOCKER_HUB_IMAGE
  build_frontend:
    docker:
      - image: docker
    working_directory: /track-expenses
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t track-expenses-frontend frontend
      - deploy:
          name: Push Docker image
          command: |
            TAG=${CIRCLE_SHA1:0:8}
            DOCKER_HUB_IMAGE=oxisto/track-expenses-frontend
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag track-expenses-frontend $DOCKER_HUB_IMAGE
            docker tag track-expenses-frontend $DOCKER_HUB_IMAGE:$TAG
            docker push $DOCKER_HUB_IMAGE:$TAG
            docker push $DOCKER_HUB_IMAGE
  deploy_kubernetes:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Download kubectl
          command: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl
      - run:
          name: Retrieve kubeconfig from ENV
          command: mkdir -p ~/.kube && echo $KUBECONFIG_BASE64 | base64 -d > ~/.kube/config
      - run:
          name: Install track-expenses frontend
          command: ./kubectl apply -f kubernetes/frontend.yaml
      - run:
          name: Install track-expenses server
          command: ./kubectl apply -f kubernetes/server.yaml
      - run:
          name: Set image to current build
          command: |
            TAG=${CIRCLE_SHA1:0:8}
            ./kubectl set image deployment frontend frontend=oxisto/track-expenses-frontend:$TAG -n track-expenses
            ./kubectl set image deployment server server=oxisto/track-expenses-server:$TAG -n track-expenses
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build_frontend:
          context: org-global
      - build_server:
          context: org-global
      - deploy_kubernetes:
          context: org-global
          requires:
            - build_frontend
            - build_server
